apiVersion: v1
entries:
  flaresolverr:
  - apiVersion: v2
    appVersion: v3.3.21
    created: "2026-05-04T19:52:14.968216481Z"
    description: FlareSolverr - Proxy server to bypass Cloudflare protection
    digest: 9db46108829702f878bc9339b5322c0f3e25273063ac1e1a8aa65725cf1d0fac
    name: flaresolverr
    type: application
    urls:
    - https://mowntan.github.io/k8s-homelab/charts/flaresolverr-1.0.0.tgz
    version: 1.0.0
  jackett:
  - apiVersion: v2
    appVersion: 0.24.1184
    created: "2026-05-04T19:52:14.968545656Z"
    description: Jackett torrent tracker proxy
    digest: 344059bcc3ec6e43bb10ef09cff8616710c5ec6d28ab1675e153b7b766d94673
    name: jackett
    type: application
    urls:
    - https://mowntan.github.io/k8s-homelab/charts/jackett-1.0.0.tgz
    version: 1.0.0
  qbittorrent:
  - apiVersion: v2
    appVersion: 4.6.3
    created: "2026-05-04T19:52:14.968985828Z"
    description: qBittorrent torrent client
    digest: d3c6fa478eba0f7e375962f90e2e9bd7689b6b066e6328808a9121d15d49941a
    name: qbittorrent
    type: application
    urls:
    - https://mowntan.github.io/k8s-homelab/charts/qbittorrent-1.0.0.tgz
    version: 1.0.0
  radarr:
  - apiVersion: v2
    appVersion: 5.16.3.9541
    created: "2026-05-04T19:52:14.969291769Z"
    description: Radarr movie collection manager
    digest: 07077eca1c39fd1cad241935dec80db1d60cf4170aa8d9727b6a723a20fa776f
    name: radarr
    type: application
    urls:
    - https://mowntan.github.io/k8s-homelab/charts/radarr-1.0.0.tgz
    version: 1.0.0
  sabnzbd:
  - apiVersion: v2
    appVersion: 4.5.5
    created: "2026-05-04T19:52:14.969632104Z"
    description: SABnzbd Usenet download client
    digest: 393591107dc103ab24031e7d028ceae84a081072b0ad3461a83e44842c989e73
    name: sabnzbd
    type: application
    urls:
    - https://mowntan.github.io/k8s-homelab/charts/sabnzbd-1.0.0.tgz
    version: 1.0.0
  sonarr:
  - apiVersion: v2
    appVersion: 4.0.11.2680
    created: "2026-05-04T19:52:14.969932405Z"
    description: Sonarr TV series collection manager
    digest: bb096bbe918f88d33a453307473a2aa1cb3d0a6424d345ad5237b43419cdb5e5
    name: sonarr
    type: application
    urls:
    - https://mowntan.github.io/k8s-homelab/charts/sonarr-1.0.0.tgz
    version: 1.0.0
generated: "2026-05-04T19:52:14.967841541Z"
